services:
  app:
    image: ${IMAGE}:${APP_TAG}
    environment:
      DATABASE_URL: 'postgres://postgres:${POSTGRES_PASSWORD}@db:5432/postgres'
    ports:
      - 127.0.0.1:3000:3000
  db:
    image: postgres:18.4-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
volumes:
  postgres_data:
